imageinfo = {
      "SingleImage": [
              {
                        "x": 0,
                              "y": 0,
                                    "width": 320,
                                          "height": 504,
                                                "rotate": None,
                                                      "animation": None,
                                                            "maskRadius": 0,
                                                                  "animation-delay": None,
                                                                        "animation-duration": None,
                                                                              "type": "image",
                                                                                    "borderWidth": 0,
                                                                                          "borderColor": None,
                                                                                                "diretion": None,
                                                                                                      "alignX": None,
                                                                                                            "alignY": None,
                                                                                                                  "opacity": None
                                                                                                                          }
        ],
              "MutipleImage01": [
                      {
                                "x": 35,
                                      "y": 61,
                                            "width": 251,
                                                  "height": 381,
                                                        "rotate": None,
                                                              "animation": None,
                                                                    "maskRadius": 0,
                                                                          "animation-delay": None,
                                                                                "animation-duration": None,
                                                                                      "type": None,
                                                                                            "borderWidth": 0,
                                                                                                  "borderColor": None,
                                                                                                        "diretion": None,
                                                                                                              "alignX": None,
                                                                                                                    "alignY": None,
                                                                                                                          "opacity": None
                                                                                                                                  }
          ],
                "scratch-card": [
                        {
                                  "x": 0,
                                        "y": 0,
                                              "width": 320,
                                                    "height": 504,
                                                          "rotate": None,
                                                                "animation": None,
                                                                      "maskRadius": 0,
                                                                            "animation-delay": None,
                                                                                  "animation-duration": None,
                                                                                        "type": "image",
                                                                                              "borderWidth": 0,
                                                                                                    "borderColor": None,
                                                                                                          "diretion": None,
                                                                                                                "alignX": None,
                                                                                                                      "alignY": None,
                                                                                                                            "opacity": None
                                                                                                                                    },
                    None
                          ],
                      "MutipleImage03": [
                              {
                                        "x": 15,
                                              "y": 15,
                                                    "width": 290,
                                                          "height": 232,
                                                                "rotate": None,
                                                                      "animation": None,
                                                                            "maskRadius": 0,
                                                                                  "animation-delay": None,
                                                                                        "animation-duration": None,
                                                                                              "type": "image",
                                                                                                    "borderWidth": 0,
                                                                                                          "borderColor": None,
                                                                                                                "diretion": None,
                                                                                                                      "alignX": None,
                                                                                                                            "alignY": None,
                                                                                                                                  "opacity": None
                                                                                                                                          },
                          {
                                    "x": 15,
                                          "y": 250,
                                                "width": 143,
                                                      "height": 240,
                                                            "rotate": None,
                                                                  "animation": None,
                                                                        "maskRadius": 0,
                                                                              "animation-delay": None,
                                                                                    "animation-duration": None,
                                                                                          "type": "image",
                                                                                                "borderWidth": 0,
                                                                                                      "borderColor": None,
                                                                                                            "diretion": None,
                                                                                                                  "alignX": None,
                                                                                                                        "alignY": None,
                                                                                                                              "opacity": None
                                                                                                                                      },
                              {
                                        "x": 162,
                                              "y": 250,
                                                    "width": 143,
                                                          "height": 240,
                                                                "rotate": None,
                                                                      "animation": None,
                                                                            "maskRadius": 0,
                                                                                  "animation-delay": None,
                                                                                        "animation-duration": None,
                                                                                              "type": "image",
                                                                                                    "borderWidth": 0,
                                                                                                          "borderColor": None,
                                                                                                                "diretion": None,
                                                                                                                      "alignX": None,
                                                                                                                            "alignY": None,
                                                                                                                                  "opacity": None
                                                                                                                                          }
            ],
                  "MutipleImage02": [
                          {
                                    "x": 15,
                                          "y": 14,
                                                "width": 293,
                                                      "height": 162,
                                                            "rotate": None,
                                                                  "animation": None,
                                                                        "maskRadius": 0,
                                                                              "animation-delay": None,
                                                                                    "animation-duration": None,
                                                                                          "type": "image",
                                                                                                "borderWidth": 0,
                                                                                                      "borderColor": None,
                                                                                                            "diretion": None,
                                                                                                                  "alignX": None,
                                                                                                                        "alignY": None,
                                                                                                                              "opacity": None
                                                                                                                                      },
                      {
                                "x": 15,
                                      "y": 175,
                                            "width": 292,
                                                  "height": 160,
                                                        "rotate": None,
                                                              "animation": None,
                                                                    "maskRadius": 0,
                                                                          "animation-delay": None,
                                                                                "animation-duration": None,
                                                                                      "type": "image",
                                                                                            "borderWidth": 0,
                                                                                                  "borderColor": None,
                                                                                                        "diretion": None,
                                                                                                              "alignX": None,
                                                                                                                    "alignY": None,
                                                                                                                          "opacity": None
                                                                                                                                  },
                          {
                                    "x": 15,
                                          "y": 330,
                                                "width": 291,
                                                      "height": 160,
                                                            "rotate": None,
                                                                  "animation": None,
                                                                        "maskRadius": 0,
                                                                              "animation-delay": None,
                                                                                    "animation-duration": None,
                                                                                          "type": "image",
                                                                                                "borderWidth": 0,
                                                                                                      "borderColor": None,
                                                                                                            "diretion": None,
                                                                                                                  "alignX": None,
                                                                                                                        "alignY": None,
                                                                                                                              "opacity": None
                                                                                                                                      }
              ],
                    "ImageText08": [
                            {
                                      "x": 0,
                                            "y": 0,
                                                  "width": 320,
                                                        "height": 504,
                                                              "rotate": None,
                                                                    "animation": None,
                                                                          "maskRadius": 0,
                                                                                "animation-delay": None,
                                                                                      "animation-duration": None,
                                                                                            "type": "image",
                                                                                                  "borderWidth": 0,
                                                                                                        "borderColor": None,
                                                                                                              "diretion": None,
                                                                                                                    "alignX": None,
                                                                                                                          "alignY": None,
                                                                                                                                "opacity": None
                                                                                                                                        },
                        {
                                  "x": 88,
                                        "y": 346,
                                              "width": 218,
                                                    "height": 35,
                                                          "rotate": None,
                                                                "animation": None,
                                                                      "maskRadius": 0,
                                                                            "animation-delay": None,
                                                                                  "animation-duration": None,
                                                                                        "type": "text",
                                                                                              "borderWidth": 0,
                                                                                                    "borderColor": None,
                                                                                                          "diretion": None,
                                                                                                                "alignX": None,
                                                                                                                      "alignY": None,
                                                                                                                            "opacity": None
                                                                                                                                    }
                ],
                      "ImageText26": [
                              {
                                        "x": 0,
                                              "y": 0,
                                                    "width": 320,
                                                          "height": 504,
                                                                "rotate": None,
                                                                      "animation": None,
                                                                            "maskRadius": 0,
                                                                                  "animation-delay": None,
                                                                                        "animation-duration": None,
                                                                                              "type": "image",
                                                                                                    "borderWidth": 0,
                                                                                                          "borderColor": None,
                                                                                                                "diretion": None,
                                                                                                                      "alignX": None,
                                                                                                                            "alignY": None,
                                                                                                                                  "opacity": None
                                                                                                                                          },
                          {
                                    "x": 12,
                                          "y": 307,
                                                "width": 163,
                                                      "height": 33,
                                                            "rotate": None,
                                                                  "animation": None,
                                                                        "maskRadius": 0,
                                                                              "animation-delay": None,
                                                                                    "animation-duration": None,
                                                                                          "type": "text",
                                                                                                "borderWidth": 0,
                                                                                                      "borderColor": None,
                                                                                                            "diretion": None,
                                                                                                                  "alignX": None,
                                                                                                                        "alignY": None,
                                                                                                                              "opacity": None
                                                                                                                                      },
                              {
                                        "x": 83,
                                              "y": 351,
                                                    "width": 138,
                                                          "height": 20,
                                                                "rotate": None,
                                                                      "animation": None,
                                                                            "maskRadius": 0,
                                                                                  "animation-delay": None,
                                                                                        "animation-duration": None,
                                                                                              "type": "text",
                                                                                                    "borderWidth": 0,
                                                                                                          "borderColor": None,
                                                                                                                "diretion": None,
                                                                                                                      "alignX": None,
                                                                                                                            "alignY": None,
                                                                                                                                  "opacity": None
                                                                                                                                          }
                  ],
                        "ImageText18": [
                                {
                                          "x": 0,
                                                "y": 0,
                                                      "width": 320,
                                                            "height": 504,
                                                                  "rotate": None,
                                                                        "animation": None,
                                                                              "maskRadius": 0,
                                                                                    "animation-delay": None,
                                                                                          "animation-duration": None,
                                                                                                "type": "image",
                                                                                                      "borderWidth": 0,
                                                                                                            "borderColor": None,
                                                                                                                  "diretion": None,
                                                                                                                        "alignX": None,
                                                                                                                              "alignY": None,
                                                                                                                                    "opacity": None
                                                                                                                                            },
                            {
                                      "x": 88,
                                            "y": 115,
                                                  "width": 142,
                                                        "height": 41,
                                                              "rotate": None,
                                                                    "animation": None,
                                                                          "maskRadius": 0,
                                                                                "animation-delay": None,
                                                                                      "animation-duration": None,
                                                                                            "type": "text",
                                                                                                  "borderWidth": 0,
                                                                                                        "borderColor": None,
                                                                                                              "diretion": None,
                                                                                                                    "alignX": None,
                                                                                                                          "alignY": None,
                                                                                                                                "opacity": None
                                                                                                                                        },
                                {
                                          "x": 118,
                                                "y": 190,
                                                      "width": 86,
                                                            "height": 14,
                                                                  "rotate": None,
                                                                        "animation": None,
                                                                              "maskRadius": 0,
                                                                                    "animation-delay": None,
                                                                                          "animation-duration": None,
                                                                                                "type": "text",
                                                                                                      "borderWidth": 0,
                                                                                                            "borderColor": None,
                                                                                                                  "diretion": None,
                                                                                                                        "alignX": None,
                                                                                                                              "alignY": None,
                                                                                                                                    "opacity": None
                                                                                                                                            },
                                    {
                                              "x": 60,
                                                    "y": 219,
                                                          "width": 203,
                                                                "height": 15,
                                                                      "rotate": None,
                                                                            "animation": None,
                                                                                  "maskRadius": 0,
                                                                                        "animation-delay": None,
                                                                                              "animation-duration": None,
                                                                                                    "type": "text",
                                                                                                          "borderWidth": 0,
                                                                                                                "borderColor": None,
                                                                                                                      "diretion": None,
                                                                                                                            "alignX": None,
                                                                                                                                  "alignY": None,
                                                                                                                                        "opacity": None
                                                                                                                                                }
                    ],
                          "ImageText17": [
                                  {
                                            "x": 0,
                                                  "y": 0,
                                                        "width": 320,
                                                              "height": 504,
                                                                    "rotate": None,
                                                                          "animation": None,
                                                                                "maskRadius": 0,
                                                                                      "animation-delay": None,
                                                                                            "animation-duration": None,
                                                                                                  "type": "image",
                                                                                                        "borderWidth": 0,
                                                                                                              "borderColor": None,
                                                                                                                    "diretion": None,
                                                                                                                          "alignX": None,
                                                                                                                                "alignY": None,
                                                                                                                                      "opacity": None
                                                                                                                                              },
                              {
                                        "x": 22,
                                              "y": 348,
                                                    "width": 57,
                                                          "height": 28,
                                                                "rotate": None,
                                                                      "animation": None,
                                                                            "maskRadius": 0,
                                                                                  "animation-delay": None,
                                                                                        "animation-duration": None,
                                                                                              "type": "text",
                                                                                                    "borderWidth": 0,
                                                                                                          "borderColor": None,
                                                                                                                "diretion": None,
                                                                                                                      "alignX": None,
                                                                                                                            "alignY": None,
                                                                                                                                  "opacity": None
                                                                                                                                          },
                                  {
                                            "x": 26,
                                                  "y": 391,
                                                        "width": 182,
                                                              "height": 43,
                                                                    "rotate": None,
                                                                          "animation": None,
                                                                                "maskRadius": 0,
                                                                                      "animation-delay": None,
                                                                                            "animation-duration": None,
                                                                                                  "type": "text",
                                                                                                        "borderWidth": 0,
                                                                                                              "borderColor": None,
                                                                                                                    "diretion": None,
                                                                                                                          "alignX": None,
                                                                                                                                "alignY": None,
                                                                                                                                      "opacity": None
                                                                                                                                              }
                      ],
                            "ImageText22": [
                                    {
                                              "x": 0,
                                                    "y": 0,
                                                          "width": 320,
                                                                "height": 504,
                                                                      "rotate": None,
                                                                            "animation": None,
                                                                                  "maskRadius": 0,
                                                                                        "animation-delay": None,
                                                                                              "animation-duration": None,
                                                                                                    "type": "image",
                                                                                                          "borderWidth": 0,
                                                                                                                "borderColor": None,
                                                                                                                      "diretion": None,
                                                                                                                            "alignX": None,
                                                                                                                                  "alignY": None,
                                                                                                                                        "opacity": None
                                                                                                                                                },
                                {
                                          "x": 258,
                                                "y": 97,
                                                      "width": 28,
                                                            "height": 84,
                                                                  "rotate": None,
                                                                        "animation": None,
                                                                              "maskRadius": 0,
                                                                                    "animation-delay": None,
                                                                                          "animation-duration": None,
                                                                                                "type": "text",
                                                                                                      "borderWidth": 0,
                                                                                                            "borderColor": None,
                                                                                                                  "diretion": None,
                                                                                                                        "alignX": None,
                                                                                                                              "alignY": None,
                                                                                                                                    "opacity": None
                                                                                                                                            },
                                    {
                                              "x": 278,
                                                    "y": 189,
                                                          "width": 15,
                                                                "height": 210,
                                                                      "rotate": None,
                                                                            "animation": None,
                                                                                  "maskRadius": 0,
                                                                                        "animation-delay": None,
                                                                                              "animation-duration": None,
                                                                                                    "type": "text",
                                                                                                          "borderWidth": 0,
                                                                                                                "borderColor": None,
                                                                                                                      "diretion": None,
                                                                                                                            "alignX": None,
                                                                                                                                  "alignY": None,
                                                                                                                                        "opacity": None
                                                                                                                                                }
                        ],
                              "ImageText23": [
                                      {
                                                "x": 0,
                                                      "y": 0,
                                                            "width": 320,
                                                                  "height": 504,
                                                                        "rotate": None,
                                                                              "animation": None,
                                                                                    "maskRadius": 0,
                                                                                          "animation-delay": None,
                                                                                                "animation-duration": None,
                                                                                                      "type": "image",
                                                                                                            "borderWidth": 0,
                                                                                                                  "borderColor": None,
                                                                                                                        "diretion": None,
                                                                                                                              "alignX": None,
                                                                                                                                    "alignY": None,
                                                                                                                                          "opacity": None
                                                                                                                                                  },
                                  {
                                            "x": 30,
                                                  "y": 70,
                                                        "width": 74,
                                                              "height": 31,
                                                                    "rotate": None,
                                                                          "animation": None,
                                                                                "maskRadius": 0,
                                                                                      "animation-delay": None,
                                                                                            "animation-duration": None,
                                                                                                  "type": "text",
                                                                                                        "borderWidth": 0,
                                                                                                              "borderColor": None,
                                                                                                                    "diretion": None,
                                                                                                                          "alignX": None,
                                                                                                                                "alignY": None,
                                                                                                                                      "opacity": None
                                                                                                                                              },
                                      {
                                                "x": 30,
                                                      "y": 113,
                                                            "width": 139,
                                                                  "height": 15,
                                                                        "rotate": None,
                                                                              "animation": None,
                                                                                    "maskRadius": 0,
                                                                                          "animation-delay": None,
                                                                                                "animation-duration": None,
                                                                                                      "type": "text",
                                                                                                            "borderWidth": 0,
                                                                                                                  "borderColor": None,
                                                                                                                        "diretion": None,
                                                                                                                              "alignX": None,
                                                                                                                                    "alignY": None,
                                                                                                                                          "opacity": None
                                                                                                                                                  }
                          ],
                                "custom": [
                                        None,
                                    {
                                              "x": 24,
                                                    "y": 33,
                                                          "width": 228,
                                                                "height": 24,
                                                                      "rotate": None,
                                                                            "animation": "fly-into-left",
                                                                                  "maskRadius": 0,
                                                                                        "animation-delay": None,
                                                                                              "animation-duration": None,
                                                                                                    "type": "text",
                                                                                                          "borderWidth": 0,
                                                                                                                "borderColor": None,
                                                                                                                      "diretion": None,
                                                                                                                            "alignX": None,
                                                                                                                                  "alignY": None,
                                                                                                                                        "opacity": None
                                                                                                                                                },
                                        {
                                                  "x": 27,
                                                        "y": 71,
                                                              "width": 251,
                                                                    "height": 108,
                                                                          "rotate": None,
                                                                                "animation": "fly-into-left",
                                                                                      "maskRadius": 0,
                                                                                            "animation-delay": None,
                                                                                                  "animation-duration": None,
                                                                                                        "type": "text",
                                                                                                              "borderWidth": 0,
                                                                                                                    "borderColor": None,
                                                                                                                          "diretion": None,
                                                                                                                                "alignX": None,
                                                                                                                                      "alignY": None,
                                                                                                                                            "opacity": None
                                                                                                                                                    },
                                            {
                                                      "x": 198,
                                                            "y": 297,
                                                                  "width": 134,
                                                                        "height": 189,
                                                                              "rotate": -0.104719751,
                                                                                    "animation": "shrink",
                                                                                          "maskRadius": 3,
                                                                                                "animation-delay": None,
                                                                                                      "animation-duration": None,
                                                                                                            "type": "image",
                                                                                                                  "borderWidth": 0,
                                                                                                                        "borderColor": None,
                                                                                                                              "diretion": None,
                                                                                                                                    "alignX": None,
                                                                                                                                          "alignY": None,
                                                                                                                                                "opacity": None
                                                                                                                                                        },
                                                {
                                                          "x": 92,
                                                                "y": 306,
                                                                      "width": 134,
                                                                            "height": 189,
                                                                                  "rotate": -0.104719751,
                                                                                        "animation": "shrink",
                                                                                              "maskRadius": 3,
                                                                                                    "animation-delay": None,
                                                                                                          "animation-duration": None,
                                                                                                                "type": "image",
                                                                                                                      "borderWidth": 0,
                                                                                                                            "borderColor": None,
                                                                                                                                  "diretion": None,
                                                                                                                                        "alignX": None,
                                                                                                                                              "alignY": None,
                                                                                                                                                    "opacity": None
                                                                                                                                                            },
                                                    {
                                                              "x": -14,
                                                                    "y": 315,
                                                                          "width": 134,
                                                                                "height": 189,
                                                                                      "rotate": -0.104719751,
                                                                                            "animation": "shrink",
                                                                                                  "maskRadius": 3,
                                                                                                        "animation-delay": None,
                                                                                                              "animation-duration": None,
                                                                                                                    "type": "image",
                                                                                                                          "borderWidth": 0,
                                                                                                                                "borderColor": None,
                                                                                                                                      "diretion": None,
                                                                                                                                            "alignX": None,
                                                                                                                                                  "alignY": None,
                                                                                                                                                        "opacity": None
                                                                                                                                                                }
                            ],
                                  "ImageText02": [
                                          {
                                                    "x": 0,
                                                          "y": 0,
                                                                "width": 320,
                                                                      "height": 390,
                                                                            "rotate": None,
                                                                                  "animation": None,
                                                                                        "maskRadius": 0,
                                                                                              "animation-delay": None,
                                                                                                    "animation-duration": None,
                                                                                                          "type": "image",
                                                                                                                "borderWidth": 0,
                                                                                                                      "borderColor": None,
                                                                                                                            "diretion": None,
                                                                                                                                  "alignX": None,
                                                                                                                                        "alignY": None,
                                                                                                                                              "opacity": None
                                                                                                                                                      }
                              ],
                                    "ImageText03": [
                                            {
                                                      "x": 0,
                                                            "y": 0,
                                                                  "width": 320,
                                                                        "height": 504,
                                                                              "rotate": None,
                                                                                    "animation": None,
                                                                                          "maskRadius": 0,
                                                                                                "animation-delay": None,
                                                                                                      "animation-duration": None,
                                                                                                            "type": "image",
                                                                                                                  "borderWidth": 0,
                                                                                                                        "borderColor": None,
                                                                                                                              "diretion": None,
                                                                                                                                    "alignX": None,
                                                                                                                                          "alignY": None,
                                                                                                                                                "opacity": None
                                                                                                                                                        }
                                ],
                                      "ImageText01": [
                                              {
                                                        "x": 0,
                                                              "y": 115,
                                                                    "width": 320,
                                                                          "height": 390,
                                                                                "rotate": None,
                                                                                      "animation": None,
                                                                                            "maskRadius": 0,
                                                                                                  "animation-delay": None,
                                                                                                        "animation-duration": None,
                                                                                                              "type": "image",
                                                                                                                    "borderWidth": 0,
                                                                                                                          "borderColor": None,
                                                                                                                                "diretion": None,
                                                                                                                                      "alignX": None,
                                                                                                                                            "alignY": None,
                                                                                                                                                  "opacity": None
                                                                                                                                                          }
                                  ],
                                        "ImageText05": [
                                                {
                                                          "x": 0,
                                                                "y": 0,
                                                                      "width": 320,
                                                                            "height": 504,
                                                                                  "rotate": None,
                                                                                        "animation": None,
                                                                                              "maskRadius": 0,
                                                                                                    "animation-delay": None,
                                                                                                          "animation-duration": None,
                                                                                                                "type": "image",
                                                                                                                      "borderWidth": 0,
                                                                                                                            "borderColor": None,
                                                                                                                                  "diretion": None,
                                                                                                                                        "alignX": None,
                                                                                                                                              "alignY": None,
                                                                                                                                                    "opacity": None
                                                                                                                                                            }
                                    ],
                                          "ImageText06": [
                                                  {
                                                            "x": 0,
                                                                  "y": 0,
                                                                        "width": 320,
                                                                              "height": 504,
                                                                                    "rotate": None,
                                                                                          "animation": None,
                                                                                                "maskRadius": 0,
                                                                                                      "animation-delay": None,
                                                                                                            "animation-duration": None,
                                                                                                                  "type": "image",
                                                                                                                        "borderWidth": 0,
                                                                                                                              "borderColor": None,
                                                                                                                                    "diretion": None,
                                                                                                                                          "alignX": None,
                                                                                                                                                "alignY": None,
                                                                                                                                                      "opacity": None
                                                                                                                                                              }
                                      ],
                                            "ImageText14": [
                                                    {
                                                              "x": 0,
                                                                    "y": 0,
                                                                          "width": 320,
                                                                                "height": 504,
                                                                                      "rotate": None,
                                                                                            "animation": None,
                                                                                                  "maskRadius": 0,
                                                                                                        "animation-delay": None,
                                                                                                              "animation-duration": None,
                                                                                                                    "type": "image",
                                                                                                                          "borderWidth": 0,
                                                                                                                                "borderColor": None,
                                                                                                                                      "diretion": None,
                                                                                                                                            "alignX": None,
                                                                                                                                                  "alignY": None,
                                                                                                                                                        "opacity": None
                                                                                                                                                                },
                                                {
                                                          "x": 115,
                                                                "y": 78,
                                                                      "width": 196,
                                                                            "height": 282,
                                                                                  "rotate": None,
                                                                                        "animation": None,
                                                                                              "maskRadius": 0,
                                                                                                    "animation-delay": None,
                                                                                                          "animation-duration": None,
                                                                                                                "type": "text",
                                                                                                                      "borderWidth": 0,
                                                                                                                            "borderColor": None,
                                                                                                                                  "diretion": None,
                                                                                                                                        "alignX": None,
                                                                                                                                              "alignY": None,
                                                                                                                                                    "opacity": None
                                                                                                                                                            }
                                        ],
                                              "ImageText04": [
                                                      {
                                                                "x": 0,
                                                                      "y": 0,
                                                                            "width": 320,
                                                                                  "height": 504,
                                                                                        "rotate": None,
                                                                                              "animation": None,
                                                                                                    "maskRadius": 0,
                                                                                                          "animation-delay": None,
                                                                                                                "animation-duration": None,
                                                                                                                      "type": "image",
                                                                                                                            "borderWidth": 0,
                                                                                                                                  "borderColor": None,
                                                                                                                                        "diretion": None,
                                                                                                                                              "alignX": None,
                                                                                                                                                    "alignY": None,
                                                                                                                                                          "opacity": None
                                                                                                                                                                  }
                                          ],
                                                "ImageText07": [
                                                        {
                                                                  "x": 0,
                                                                        "y": 0,
                                                                              "width": 320,
                                                                                    "height": 504,
                                                                                          "rotate": None,
                                                                                                "animation": None,
                                                                                                      "maskRadius": 0,
                                                                                                            "animation-delay": None,
                                                                                                                  "animation-duration": None,
                                                                                                                        "type": "image",
                                                                                                                              "borderWidth": 0,
                                                                                                                                    "borderColor": None,
                                                                                                                                          "diretion": None,
                                                                                                                                                "alignX": None,
                                                                                                                                                      "alignY": None,
                                                                                                                                                            "opacity": None
                                                                                                                                                                    }
                                            ],
                                                  "Sign-Up02": [
                                                          {
                                                                    "x": 0,
                                                                          "y": 0,
                                                                                "width": 320,
                                                                                      "height": 504,
                                                                                            "rotate": None,
                                                                                                  "animation": None,
                                                                                                        "maskRadius": 0,
                                                                                                              "animation-delay": None,
                                                                                                                    "animation-duration": None,
                                                                                                                          "type": "image",
                                                                                                                                "borderWidth": 0,
                                                                                                                                      "borderColor": None,
                                                                                                                                            "diretion": None,
                                                                                                                                                  "alignX": None,
                                                                                                                                                        "alignY": None,
                                                                                                                                                              "opacity": None
                                                                                                                                                                      }
                                              ],
                                                    "video": [
                                                            {
                                                                      "x": 0,
                                                                            "y": 0,
                                                                                  "width": 320,
                                                                                        "height": 504,
                                                                                              "rotate": None,
                                                                                                    "animation": None,
                                                                                                          "maskRadius": 0,
                                                                                                                "animation-delay": None,
                                                                                                                      "animation-duration": None,
                                                                                                                            "type": "image",
                                                                                                                                  "borderWidth": 0,
                                                                                                                                        "borderColor": None,
                                                                                                                                              "diretion": None,
                                                                                                                                                    "alignX": None,
                                                                                                                                                          "alignY": None,
                                                                                                                                                                "opacity": None
                                                                                                                                                                        }
                                                ],
                                                      "ImageText16": [
                                                              {
                                                                        "x": 0,
                                                                              "y": 0,
                                                                                    "width": 320,
                                                                                          "height": 504,
                                                                                                "rotate": None,
                                                                                                      "animation": None,
                                                                                                            "maskRadius": 0,
                                                                                                                  "animation-delay": None,
                                                                                                                        "animation-duration": None,
                                                                                                                              "type": "image",
                                                                                                                                    "borderWidth": 0,
                                                                                                                                          "borderColor": None,
                                                                                                                                                "diretion": None,
                                                                                                                                                      "alignX": None,
                                                                                                                                                            "alignY": None,
                                                                                                                                                                  "opacity": None
                                                                                                                                                                          },
                                                          {
                                                                    "x": 152,
                                                                          "y": 57,
                                                                                "width": 110,
                                                                                      "height": 28,
                                                                                            "rotate": None,
                                                                                                  "animation": None,
                                                                                                        "maskRadius": 0,
                                                                                                              "animation-delay": None,
                                                                                                                    "animation-duration": None,
                                                                                                                          "type": "text",
                                                                                                                                "borderWidth": 0,
                                                                                                                                      "borderColor": None,
                                                                                                                                            "diretion": None,
                                                                                                                                                  "alignX": None,
                                                                                                                                                        "alignY": None,
                                                                                                                                                              "opacity": None
                                                                                                                                                                      },
                                                              {
                                                                        "x": 158,
                                                                              "y": 100,
                                                                                    "width": 137,
                                                                                          "height": 27,
                                                                                                "rotate": None,
                                                                                                      "animation": None,
                                                                                                            "maskRadius": 0,
                                                                                                                  "animation-delay": None,
                                                                                                                        "animation-duration": None,
                                                                                                                              "type": "text",
                                                                                                                                    "borderWidth": 0,
                                                                                                                                          "borderColor": None,
                                                                                                                                                "diretion": None,
                                                                                                                                                      "alignX": None,
                                                                                                                                                            "alignY": None,
                                                                                                                                                                  "opacity": None
                                                                                                                                                                          }
                                                  ]
}
